Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
"GET / HTTP/1.1" 500 91349
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
"GET /favicon.ico HTTP/1.1" 500 91252
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4213
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
"GET /static/admin/css/base.css HTTP/1.1" 200 21310
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18559
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
"GET /favicon.ico HTTP/1.1" 500 91277
Watching for file changes with StatReloader
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 16724
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
"GET /favicon.ico HTTP/1.1" 500 91421
C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\pristineprimer\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 16724
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\pristineprimer\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\properties\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\User1\Real_Estate_Gabby_The_Developer\real-estate-Gabby\server\newsletter\admin.py changed, reloading.
Watching for file changes with StatReloader
